Repository jotaesteves/federated-modules-monorepo, pull requests merged in 2025-08, with the labels that each got.

#16 fix: card tabs component styles
  CLAUDE.md
  apps/assetsProducts/src/components/AssetsBreadcrumbs/AssetsBreadcrumbs.tsx
  apps/vision360/src/components/cards/LastContact.tsx
  apps/vision360/src/components/cards/LastContact/LastContact.tsx
  packages/shared/src/assets/icons/HistoryIcon.tsx
  packages/shared/src/assets/icons/index.ts
  packages/shared/src/components/Card/Card.tsx
  packages/shared/src/components/Icon/Icon.tsx
  packages/shared/src/components/ui/card.tsx
  packages/shared/src/components/ui/tabs.tsx
  packages/shared/src/styles/GlobalStyles.tsx
  packages/shared/src/styles/TailwindProvider.tsx
  packages/shared/src/styles/globals.css
  packages/shared/tailwind.config.js
Labels: bug, enhancement

#41 refactor: update react-router dependency and adjust imports
  ADDING_NEW_MICROFRONTEND.md
  apps/assetsProducts/package.json
  apps/assetsProducts/src/bootstrap.tsx
  apps/channelsAndServices/package.json
  apps/channelsAndServices/src/bootstrap.tsx
  apps/channelsAndServices/src/pages/page1/Page1.test.tsx
  apps/channelsAndServices/src/pages/page1/Page1.tsx
  apps/channelsAndServices/src/pages/page2/Page2.test.tsx
  apps/channelsAndServices/src/pages/page2/Page2.tsx
  apps/footer/package.json
  apps/footer/src/bootstrap.tsx
  apps/header/package.json
  apps/header/src/bootstrap.tsx
  apps/header/src/components/HeaderTabs.tsx
  apps/historyInteractions/package.json
  apps/historyInteractions/src/bootstrap.tsx
  apps/main/package.json
  apps/main/src/App.tsx
  apps/main/src/bootstrap.tsx
  apps/main/src/components/NavBar/NavBar.test.tsx
  apps/main/src/components/NavBar/NavBar.tsx
  apps/main/src/layouts/BaseLayout.tsx
  apps/main/src/layouts/DashboardLayout.tsx
  apps/main/src/layouts/SidebarLayout.tsx
  apps/personalData/package.json
  apps/personalData/src/bootstrap.tsx
  apps/personalData/src/pages/page1/Page1.test.tsx
  apps/personalData/src/pages/page1/Page1.tsx
  apps/personalData/src/pages/page2/Page2.test.tsx
  apps/personalData/src/pages/page2/Page2.tsx
  apps/records/package.json
  apps/records/src/bootstrap.tsx
  apps/vision360/package.json
  bun.lock
  packages/@config/webpack-config/enums.ts
  packages/shared/package.json
  turbo.json
Labels: enhancement

#50 fix(main): fix module
  .husky/pre-commit
  .lintstagedrc.json
  apps/documentation/package.json
  apps/documentation/src/bootstrap.tsx
  apps/header/src/data/menuData.ts
  apps/home/package.json
  apps/home/webpack/webpack.common.ts
  apps/home/webpack/webpack.dev.ts
  apps/home/webpack/webpack.prod.ts
  apps/kpi/package.json
  apps/kpi/src/bootstrap.tsx
  apps/outbounds/package.json
  apps/outbounds/src/bootstrap.tsx
  apps/sales/package.json
  apps/sales/src/bootstrap.tsx
  apps/scriptsView/package.json
  apps/scriptsView/src/bootstrap.tsx
  apps/settingsView/src/bootstrap.tsx
  bun.lock
  packages/@config/webpack-config/module-federation.ts
Labels: bug

#69 feat: change sidebar open-close logic
  apps/header/src/Sidebar.tsx
  apps/header/src/components/Menu.tsx
  apps/header/src/components/Submenu.tsx
  apps/header/src/types/types.ts
Labels: enhancement

#68 feat: add TooltipComponent
  packages/shared/package.json
  packages/shared/src/components/Tooltip/TooltipComponent.tsx
  packages/shared/src/components/Tooltip/index.ts
  packages/shared/src/components/ui/tooltip.tsx
  packages/shared/tailwind.config.js
Labels: enhancement

#65 feat: add Channels and Services component with mock data
  apps/footer/src/Footer.tsx
  apps/header/src/Header.tsx
  apps/personalData/src/PersonalData.tsx
  apps/personalData/src/components/cards/Addresses/Addresses.tsx
  apps/personalData/src/components/cards/Addresses/mock-data/mock-data.json
  apps/personalData/src/components/cards/ChannelsAndServices.tsx
  apps/personalData/src/components/cards/ClientData/ClientData.tsx
  apps/personalData/src/components/cards/ClientData/mock-data/mock-data.json
  apps/personalData/src/components/cards/Contacts/Contacts.tsx
  apps/personalData/src/components/cards/Contacts/mock-data/mock-data.json
  apps/personalData/src/components/cards/Documentation/Documentation.tsx
  apps/personalData/src/components/cards/Documentation/mock-data/mock-data.json
  apps/personalData/src/components/cards/EstateAndProducts.tsx
  apps/personalData/src/components/cards/FinancialData/FinancialData.tsx
  apps/personalData/src/components/cards/FinancialData/mock-data/mock-data.json
  apps/personalData/src/components/cards/Incidents.tsx
  apps/personalData/src/components/cards/LastContact.tsx
  apps/personalData/src/components/cards/PersonalData.tsx
  apps/personalData/src/components/cards/PersonalData/PersonalData.tsx
  apps/personalData/src/components/cards/PersonalData/mock-data/mock-data.json
  apps/personalData/src/components/cards/RiskData/RiskData.tsx
  apps/personalData/src/components/cards/RiskData/mock-data/mock-data.json
  apps/personalData/src/global.css
  apps/vision360/src/Vision360.tsx
  apps/vision360/src/components/cards/ChannelsAndServices.tsx
  apps/vision360/src/components/cards/ChannelsAndServices/ChannelsAndServices.tsx
  apps/vision360/src/components/cards/ChannelsAndServices/mock-data/mock-data.json
  apps/vision360/src/components/cards/EstateAndProducts.tsx
  apps/vision360/src/components/cards/EstateAndProducts/EstateAndProducts.tsx
  apps/vision360/src/components/cards/EstateAndProducts/mock-data/mock-data.json
  apps/vision360/src/components/cards/EstateAndProducts/types.ts
  apps/vision360/src/components/cards/Incidents/Incidents.tsx
  apps/vision360/src/components/cards/LastContact.tsx
  apps/vision360/src/components/cards/LastContact/LastContact.tsx
  apps/vision360/src/components/cards/PersonalData.tsx
  apps/vision360/src/components/cards/PersonalData/PersonalData.tsx
  apps/vision360/src/components/cards/PersonalData/mock-data/mock-data.json
  packages/@config/tsconfig/tsconfig.json
  packages/shared/src/assets/icons/AnalyticsBusinessChartIcon.tsx
  packages/shared/src/assets/icons/BoxIcon.tsx
  packages/shared/src/assets/icons/ContactsIcon.tsx
  packages/shared/src/assets/icons/DangerIcon.tsx
  packages/shared/src/assets/icons/DocumentLayoutIcon.tsx
  packages/shared/src/assets/icons/LocationIcon.tsx
  packages/shared/src/assets/icons/PersonalIcon.tsx
  packages/shared/src/assets/icons/PersonalQuestionIcon.tsx
  packages/shared/src/assets/icons/PieChartIcon.tsx
  packages/shared/src/assets/icons/index.ts
  packages/shared/src/components/Card/Card.tsx
  packages/shared/src/components/Card/CardTabs.tsx
  packages/shared/src/components/CardItem/CardItemLabel.tsx
  packages/shared/src/components/Icon/Icon.tsx
  packages/shared/src/components/ui/accordion.tsx
  packages/shared/src/components/ui/card.tsx
  packages/shared/tailwind.config.js
Labels: enhancement
